# URL to start scraping from
url: https://www.screener.in/full-text-search/?q=%22board+meeting%22+and+%22Qualified+Institutions+Placement%22+and+%22consider%22&type=announcements

# Reusable browser session name
session: "default"

# Optional request headers
headers:
  Referer: https://www.screener.in/login/
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
  Content-Type: application/x-www-form-urlencoded
  Origin: https://www.screener.in

# Login section: fill fields and submit
login:
  enabled: true
  url: https://www.screener.in/login/
  actions:
    - type: fill
      selector: "input[name='username']"
      value: shubhamsethi@outlook.com
    - type: fill
      selector: "input[name='password']"
      value: Sammed@55
    - type: click
      selector: "button[type='submit']"

# Pagination support
pagination:
  param: page
  start: 1
  end: 3

# Extraction schema
extract:
  announcements:
    type: group
    multiple: true
    container: "div[class*='margin-top-20'][class*='margin-bottom-36']"
    fields:
      company_name:
        type: css
        query: "span.hover-link.ink-900"
      title:
        type: css
        query: "div.font-size-17.font-weight-500 > a"
      announcement_url:
        type: css
        query: "div.font-size-17.font-weight-500 > a"
        attribute: href
      detail:
        type: css
        query: "div.ink-700.font-size-16"
      announcement_date:
        type: css
        query: "div.margin-top-4.ink-700.font-size-14"

# Output format: json or markdown
output_format: "json"

# If true, will crawl entire rendered page HTML/DOM
full_page: false