url: https://www.screener.in/full-text-search/?q=%22board+meeting%22+and+%22Qualified+Institutions+Placement%22+and+%22consider%22&type=announcements
headers:
  Referer: https://www.screener.in/login/
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
  Content-Type: application/x-www-form-urlencoded
  Origin: https://www.screener.in
login:
  enabled: true
  type: form         # form or 'javascript'
  url: https://www.screener.in/login/
  csrf_field: csrfmiddlewaretoken  # name of the hidden input
  csrf_source: html                # html or 'cookie' or 'header'
  username_field: username
  password_field: password
  credentials:
    username: shubhamsethi@outlook.com
    password: Sammed@55
selectors:
  announcements:
    type: group
    multiple: true
    container: "div[class*='margin-top-20'][class*='margin-bottom-36']"
    fields:
      company_name:
        type: css
        query: "span.hover-link.ink-900"
      title:
        type: css
        query: "div.font-size-17.font-weight-500 > a"
      announcement_url:
        type: css
        query: "div.font-size-17.font-weight-500 > a"
        attribute: href
      detail:
        type: css
        query: "div.ink-700.font-size-16"
      announcement_date:
        type: css
        query: "div.margin-top-4.ink-700.font-size-14"

pagination:
  type: param                      # options: param (e.g., ?page=2), TODO: can extend to link or JS click in future
  param: page
  appender: "&"                   # Options: ?, &, / or custom (like -)
  start: 1
  end: 3
  step: 1
output:
  format: json                    # options: json / csv (if extended)
  path: scraped_output.json