# LLM Selector Generator Configuration for Crawl4AI Scraper
llm_selectors:
  enabled: true

  # LLM provider: anthropic or openai
  llm_provider: "anthropic"

  # Model to use
  llm_model: "claude-3-haiku-20240307"  # claude-3-haiku, claude-3-sonnet, claude-3-opus, or gpt-4, etc.

  # API key (or use environment variable)
  # llm_api_key: "your_api_key_here"

  # API endpoint (defaults are typically correct)
  # llm_api_url: "https://api.anthropic.com/v1/messages"  # for Anthropic
  # llm_api_url: "https://api.openai.com/v1/chat/completions"  # for OpenAI

  # Maximum HTML length to send to LLM
  max_html_length: 12000

  # Caching options
  use_cache: true
  cache_dir: "selector_cache"

  # Generate selectors on startup
  generate_on_start: true

  # Extraction specification - tells the LLM what to extract
  # This will be used to generate the selectors automatically
extraction_spec:
  # Format 1: Simple fields (not in a group)
  title: null
  price: null
  description: null

  # Format 2: Group with fields
  products:
    - name
    - price
    - image_url
    - description

  related_items:
    - title
    - url