extract:
  VP Posts:
    multiple: true
    query: body > section.ember-application > div.discourse-root.ember-view:nth-child(1)
      > div.wrap:nth-child(3) > div:nth-child(2) > div.regular.ember-view:nth-child(2)
      > div.container.posts:nth-child(3) > div.row:nth-child(3) > section.topic-area
      > div.posts-wrapper:nth-child(1) > div.ember-view:nth-child(2) > div.post-stream
      > div.topic-post.clearfix:nth-child(1) > article.boxed.onscreen-post > div.row:nth-child(1)
    type: css
headers:
  Accept: '*/*'
  Accept-Language: en-US,en;q=0.9
  Referer: https://forum.valuepickr.com/t/pondy-oxide-chemicals/1133
  User-Agent: ''
  content-type: application/x-www-form-urlencoded; charset=UTF-8
  discourse-deferred-track-view: 'true'
  discourse-deferred-track-view-topic-id: '1133'
  discourse-present: 'true'
  sec-ch-ua: '"Not:A-Brand";v="24", "Chromium";v="134"'
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: '"macOS"'
  upgrade-insecure-requests: '1'
  x-csrf-token: undefined
  x-requested-with: XMLHttpRequest
  x-silence-logger: 'true'
output_dir: output
output_format: json
render_js: true
stealth_mode: true
url: https://forum.valuepickr.com/t/pondy-oxide-chemicals/1133
