extract:
  title:
    multiple: false
    query: body > center > table > tbody > tr:nth-child(3) > td > table > tbody >
      tr.athing.submission:nth-child(4) > td.title:nth-child(3) > span.titleline >
      a
    type: css
headers:
  Accept: '*/*'
  Accept-Language: en-US,en;q=0.9
  Referer: https://news.ycombinator.com/
  User-Agent: ''
  sec-ch-ua: '"Not:A-Brand";v="24", "Chromium";v="134"'
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: '"macOS"'
  upgrade-insecure-requests: '1'
output_dir: output
output_format: json
render_js: true
stealth_mode: true
url: https://news.ycombinator.com/
